import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ReactNode } from 'react'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/sidabar/app-sidebar'
import NavBar from '@/components/nav/navBar'

const satoshiFont = localFont({
  src: './fonts/Satoshi-Variable.woff2',
  variable: '--font-satoshi'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={satoshiFont.className}>
        <SidebarProvider>
          <AppSidebar />
          <main className='w-full h-svh'>
            <NavBar />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
